language: php

php:
  - 5.5
services:
  - mysql

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # Install global composer dependencies.
  - composer global require --prefer-dist --no-interaction drush/drush:6.* phing/phing:2.7.* youngj/httpserver:dev-master#aabdd56e2be82c12c313b236cee94da1fa3401a2
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Prepare build and install composer dependencies
  - cp build.travis.properties build.properties
  - phing prepare:all

  # Build the codebase.
  - phing make

  # Disable sendmail.
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Mysql.
  - mysql -uroot -proot -hmysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -uroot -proot -hmysql -e 'SET GLOBAL innodb_fast_shutdown=0;'
  - mysql -uroot -proot -hmysql -e 'CREATE DATABASE drupal;'
  - mysql -uroot -proot -hmysql -e 'GRANT ALL PRIVILEGES ON drupal.* TO "drupal"@"%" IDENTIFIED BY "drupal";'
  - mysql -uroot -proot -hmysql -e 'FLUSH PRIVILEGES;'

before_script:
  - phing site-install -Ddb.name=drupal -Ddb.username=drupal -Ddb.password=drupal -Ddb.host=mysql

  # Start the server.
  - cd ../agov-build && drush runserver 80 &
  - until netstat -an 2>/dev/null | grep '80.*LISTEN'; do true; done
