<?php

/**
 * @file
 * Provides core functionality for agov_menu_block.
 */

/**
 * Implements hook_menu_block_blocks().
 */
function agov_menu_block_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'agov_menu_block-main-menu' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Main Menu (Expanded)',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 1,
      'sort'        => 0,
    ),
    'agov_menu_block-footer' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Footer Menu',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 1,
      'sort'        => 0,
    ),
    'agov_menu_block-sidebar' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 1,
      'admin_title' => '',
      'level'       => 2,
      'follow'      => 0,
      'depth'       => 2,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}

/**
 * Implements hook_block_view_alter().
 */
function agov_menu_block_block_view_alter(&$data, $block) {
  if ($block->module == 'menu_block'  && $block->delta == 'agov_menu_block-sidebar') {
    // Display the sidebar menu even if there are no children. We can hide it
    // via the UI if we don't want it.
    if (variable_get('agov_always_show_menu', TRUE) == TRUE && empty($data['content'])) {
      $data['content'] = '&nbsp;';
    }
  }
}
